<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '"{path}" is not a valid directory.' => '"{path}" වලංගු folder ක් නොවේ.',
  '&lt; Previous' => '&lt; පෙර',
  '&lt;&lt; First' => '&lt;&lt; පළමු',
  'Either "{parent}" or "{child}" does not exist.' => '"{parent}" හෝ "{child}" නොපවතී.',
  'Go to page: ' => 'පිටුවට යන්න: ',
  'Invalid operator "{operator}".' => '"{operator}" වැරදි ක්‍රියාකරවන්නෙකි.',
  'Last &gt;&gt;' => 'අවසන් &gt;&gt;',
  'Login Required' => 'පද්ධතියට ප්‍රවේශවීම අත්‍යාවශයි',
  'Next &gt;' => 'ඊළඟ &gt;',
  'Please fix the following input errors:' => 'කරුණාකර පහත වැරදි නිවැරදි කරන්න:',
  'The file "{file}" cannot be uploaded. Only files with these extensions are allowed: {extensions}.' => '"{file}" ඇතුලුකළ නොහැකිය. {extensions} වර්ගයේ file පමණක් ඇතුලුකිරීම සඳහා වලංගුවේ.',
  'The file "{file}" is too large. Its size cannot exceed {limit} bytes.' => '"{file}" පමණට වඩා විශාල. උපරිම විශාලත්වය {limit} bytes කි.',
  'The file "{file}" is too small. Its size cannot be smaller than {limit} bytes.' => '"{file}" පමණට වඩා කුඩාය. අවමය {limit} bytes.',
  'The file "{file}" was only partially uploaded.' => '"{file}" අසම්පූර්ණ ලෙස upload වී ඇත.',
  'The queue is empty.' => 'පෝලිම හිස්ය.',
  'The system is unable to find the requested action "{action}".' => 'පද්ධතිය "{action}" සොයාගැනීමට අසමත්වුනි.',
  'The verification code is incorrect.' => 'සත්‍යාපන කේතය වැරදිය.',
  'Unable to write file "{file}".' => '"{file}" ට ලිවීමට නොහැකිවිය.',
  'Unknown type "{type}".' => '"{type}" නොහඳුනන වර්ගයකි.',
  'You are not authorized to perform this action.' => 'ඔබට මෙම ක්‍රියාව සඳහා අවසර නැත.',
  'Your request is not valid.' => 'ඔබේගේ ඉල්ලීම වලංගු නැත.',
  '{attribute} "{value}" has already been taken.' => '{attribute} "{value}" දැනටමත් ලබගෙන ඇත.',
  '{attribute} "{value}" is invalid.' => 'Значення "{value}" {attribute} වැරදිය.',
  '{attribute} cannot accept more than {limit} files.' => '{attribute} සඳහා {limit}ට වඩා පිළිගැනීමට නොහැක.',
  '{attribute} cannot be blank.' => '{attribute} අත්‍යාවශයි.',
  '{attribute} is invalid.' => '{attribute} වැරදියි.',
  '{attribute} is not a valid URL.' => '{attribute} නිවැරදි ආකාරයේ URLයක් නොවේ.',
  '{attribute} is not a valid email address.' => '{attribute} වැරදි විද්‍යුත් ලිපිනයකි.',
  '{attribute} is not in the list.' => '{attribute} ලැයිස්තුවේ නැත.',
  '{attribute} is of the wrong length (should be {length} characters).' => '{attribute} අකුරු දිග වැරදිය. (අකුරු {length} දිගින් යුක්ත විය යුතුය).',
  '{attribute} is too big (maximum is {max}).' => '{attribute} විශාලය. (උපරිම විශාලත්වය {max}කි).',
  '{attribute} is too long (maximum is {max} characters).' => '{attribute} පමණට වඩා දිගය (උපරිම අකුරු ගණන {max}කි).',
  '{attribute} is too short (minimum is {min} characters).' => '{attribute} කෙටිය. (අවම දිග {min}කි).',
  '{attribute} is too small (minimum is {min}).' => '{attribute} පමණට වඩා කුඩාය (අවමය {min}කි).',
  '{attribute} must be a number.' => '{attribute} සංඛ්‍යාවක් විය යුතුය.',
  '{attribute} must be an integer.' => '{attribute} සම්පූර්ණ සංඛ්‍යාවක් වියයුතුය.',
  '{attribute} must be repeated exactly.' => '{attribute} ඒ අයුරින්ම නැවත ඇතුලත්විය යුතුය.',
  '{attribute} must be {type}.' => '{attribute}, {type} ආකාරටය් වියයුතුය.',
  '{attribute} must be either {true} or {false}.' => '{attribute}, {true} හෝ {false} වියයුතුය.',
  '{attribute} must be greater than "{compareValue}".' => '{attribute}, "{compareValue}"ට වඩා විශාල විය යුතුය.',
  '{attribute} must be greater than or equal to "{compareValue}".' => '{attribute}, "{compareValue}"ට වඩා විශාල හෝ සමාන වියයුතුය.',
  '{attribute} must be less than "{compareValue}".' => 'Атрибут {attribute}, "{compareValue}"ට වඩා කුඩා වියයුතුය.',
  '{attribute} must be less than or equal to "{compareValue}".' => '{attribute}, "{compareValue}"ට වඩා කුඩා හෝ සමාන වියයුතුය.',
  '{attribute} must be {value}.' => '{attribute}හි අගය {value} විය යුතුය.',
  '{attribute} must not be equal to "{compareValue}".' => '{attribute}, "{compareValue}" සමාන නොවිය යුතුය.',
  '{className} does not support add() functionality.' => '{className}, add() ක්‍රියාව සඳහා සහාය නොදක්වයි.',
  '{className} does not support delete() functionality.' => '{className}, delete() ක්‍රියාව සඳහා සහාය නොදක්වයි.',
  '{className} does not support flush() functionality.' => '{className}, flush() ක්‍රියාව සඳහා සහාය නොදක්වයි.',
  '{className} does not support get() functionality.' => '{className}, get() ක්‍රියාව සඳහා සහාය නොදක්වයි.',
  '{className} does not support set() functionality.' => '{className}, set() ක්‍රියාව සඳහා සහාය නොදක්වයි.',
  '{class} does not have attribute "{name}".' => '{class}හි "{attribute}" නොමැත.',
  '{class} does not have attribute named "{name}".' => '{class}හි නමින්"{name}" නොමැත.',
  '{class} does not have a method named "{name}".' => '{class}හි "{name}"ක්‍රම වේදය නැත.',
  '{class} does not have relation "{name}".' => '{class}හි "{name}" සබඳතාවක් නැත.',
  '{class} does not support fetching all table names.' => '{class}ය සියලු වගු ගෙන්වා ගැනීම සඳහා සහාය නොදක්වයි.',
  'Unable to resolve the request "{route}".' => 'කණගාටුයි "{route}" සොයාගත නොහැක.',
  'The format of {attribute} is invalid.' => '{attribute}යේ සැකැස්ම වැරදිය',
);
