<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'මෙම අයිතමය මකා දැමීමට අවශ්‍යද?',
  'Home' => 'ප්‍රධාන පුවරුව',
  'Delete' => 'මකන්න',
  'Displaying {start}-{end} of {count} result(s).' => '{start}-{end} දක්වා දත්ත {count} අතරින්.',
  'No results found.' => 'කිසිඳු වාර්ථාවක් ඇතුලත් කර නැත.',
  'Not set' => 'සකසා නැත',
  'Sort by: ' => 'පිළිවෙල:',
  'Total {count} result(s).' => 'මුළු {count} ප්‍රතිඵල',
  'Update' => 'යාවත්කාලීන',
  'View' => 'බලන්න',
);
